run:
  timeout: 5m
  tests: false
linters:
  disable-all: false
  enable:
    - funlen
    - dogsled
    - dupl
    - lll
    - whitespace
    - wsl
    - exportloopref
  disable:
    - scopelint
    - deadcode
    - structcheck
    - varcheck
    - musttag
  presets:
    - bugs
    - unused
  fast: false
